# Generated by Django 5.0 on 2023-12-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalnigam_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('meter_id', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=200)),
                ('pressure', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='MeterID',
        ),
    ]
