# Generated by Django 5.0 on 2023-12-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalnigam_dashboard', '0002_file_delete_meterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
