# Generated by Django 5.0 on 2023-12-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalnigam_dashboard', '0003_alter_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='meter_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='device_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='meter_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='pressure',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
